version: '3.9'
# new !

services:
  backend:
    build: ./backend
    container_name: taskflow-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    restart: always
    ports:
      - '3000:80'

  nginx:
    image: nginx:alpine
    container_name: taskflow-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/taskflow-nikola.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
