version: '3.9'

services:
  backend:
    build: ./backend
    container_name: taskflow-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '4000:4000' # backend HTTP port
    networks:
      - tasknet

  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    restart: always
    # frontend SE NE IZLAŽE NA HOST — služi ga nginx container
    networks:
      - tasknet

  nginx:
    image: nginx:alpine
    container_name: taskflow-nginx
    restart: always
    ports:
      - '8080:80' # host koristi samo port 8080 (HTTP)
    volumes:
      - ./nginx/taskflow-nikola.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - tasknet

networks:
  tasknet:
