version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    ports:
      - '8080:80'

  backend:
    build: ./backend
    container_name: taskflow-backend
    ports:
      - '4000:4000'
